FROM mcr.microsoft.com/mssql/server:2019-latest

USER root

# Set environment variables **before installing packages**
ENV ACCEPT_EULA=Y \
    DEBIAN_FRONTEND=noninteractive

# Install tools non-interactively
RUN apt-get update && \
    apt-get install -y curl apt-transport-https gnupg2 && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-tools.list && \
    apt-get update && \
    apt-get install -y mssql-tools unixodbc-dev -o Dpkg::Options::="--force-overwrite" && \
    echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy init script
COPY sql/init.sql /app/src/sql/init.sql
COPY sql/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]