version: "3.9"

services:
  sqlserver:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.mssql
    container_name: sql_server
    environment:
      SA_PASSWORD: "Password123@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always

  express:
    build: .
    container_name: express_app
    environment:
      DB_USER: sa
      DB_PASS: Password123@
      DB_HOST: sqlserver
      DB_NAME: DemoDB
    ports:
      - "3000:3000"
    depends_on:
      - sqlserver
    restart: always

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins_server
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    restart: always

volumes:
  sql_data:
  jenkins_home:
