FROM jenkins/jenkins:lts-jdk17

USER root

# Install Docker CLI, Node.js, npm, dan Git
RUN apt-get update \
    && apt-get install -y lsb-release curl gnupg git \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list \
    && apt-get update \
    && apt-get install -y docker-ce-cli \
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

# Tambahkan jenkins ke docker group
RUN groupadd docker || true \
    && usermod -aG docker jenkins

USER jenkins
